package calc;


//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 14 21:21:56 BRT 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int NUMBER = 9;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int DIVIDED = 6;
  public static final int error = 1;
  public static final int RPAREN = 8;
  public static final int TIMES = 5;
  public static final int LPAREN = 7;
}

