
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 18 19:07:16 BRT 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int SUBTRACAO = 20;
  public static final int MULTIPLICACAO = 18;
  public static final int ATE = 9;
  public static final int SENAO = 4;
  public static final int ENTAO = 3;
  public static final int IGUAL = 19;
  public static final int MAIORQ = 14;
  public static final int NUMERO_NCIENTIFICA = 34;
  public static final int ESCREVA = 11;
  public static final int NUMERO_FLUTUANTE = 33;
  public static final int MENORQ = 15;
  public static final int ID = 28;
  public static final int VIRGULA = 29;
  public static final int INTEIRO = 25;
  public static final int ATRIBUICAO = 12;
  public static final int DCOLCHETES = 27;
  public static final int DPARENTESES = 17;
  public static final int EOF = 0;
  public static final int DOISPONTOS = 13;
  public static final int DIFERENTE = 30;
  public static final int NUMERO_INTEIRO = 32;
  public static final int ADICAO = 21;
  public static final int RETORNA = 8;
  public static final int DIVISAO = 22;
  public static final int FLUTUANTE = 7;
  public static final int NUMERO = 31;
  public static final int error = 1;
  public static final int EPARENTESES = 16;
  public static final int MAIORIGUALQ = 24;
  public static final int SE = 2;
  public static final int MENORIGUALQ = 23;
  public static final int ECOLCHETES = 26;
  public static final int FIM = 5;
  public static final int LEIA = 10;
  public static final int REPITA = 6;
}

